[build-system]
requires = [
	"setuptools>=77",
	"setuptools_scm[toml]>=3.4.1",
	# jaraco/skeleton#174
	"coherent.licensed",
]
build-backend = "setuptools.build_meta"

[project]
name = "jaraco.text"
authors = [{ name = "Jason R. Coombs", email = "jaraco@jaraco.com" }]
description = "Module for text manipulation"
readme = "README.rst"
classifiers = [
	"Development Status :: 5 - Production/Stable",
	"Intended Audience :: Developers",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3 :: Only",
]
requires-python = ">=3.9"
license = "MIT"
dependencies = [
	"jaraco.functools",
	"jaraco.context >= 4.1",
	'importlib_resources; python_version < "3.9"',
	"autocommand",
	"more_itertools",
]
dynamic = ["version"]

[project.urls]
Source = "https://github.com/jaraco/jaraco.text"

[project.optional-dependencies]
test = [
	# upstream
	"pytest >= 6, != 8.1.*",

	# local
	'pathlib2; python_version < "3.10"',
]

doc = [
	# upstream
	"sphinx >= 3.5",
	"jaraco.packaging >= 9.3",
	"rst.linker >= 1.9",
	"furo",
	"sphinx-lint",

	# tidelift
	"jaraco.tidelift >= 1.4",

	# local
]
inflect = ["inflect"]

check = ["pytest-checkdocs >= 2.4", "pytest-ruff >= 0.2.1; sys_platform != 'cygwin'"]

cover = ["pytest-cov"]

enabler = ["pytest-enabler >= 2.2"]

type = [
	# upstream
	"pytest-mypy",

	# local
]

[tool.setuptools_scm]
